name: DevOps-Normal

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ServiceNowDevOpsChange:
    runs-on: ubuntu-latest
    name: DevOps (Normal) Change

    steps:
      # -----------------------------------
      # CHECKOUT
      # -----------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------------------
      # CREATE STANDARD CHANGE
      # -----------------------------------
      - name: Create ServiceNow Standard Change
        id: sn_change
        uses: ServiceNow/servicenow-devops-change@v6.1.0
        with:
          devops-integration-user-name:     ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: "DevOps (Normal) Change"

          change-request: >
            {
              "autoCloseChange": "true",
              "attributes": {
                "short_description": "Test 123",
                "description": "Production change?\n\nQuality of plans: Implementation, Rollback, Test, Validation & communication\n\nService Disruption expected?\n\nTests successful\n\nTechnical Approvals to deploy in prod\n\nProduct owner approval\n\nSecurity Approval (assessment)\n\nChange successful before\n\nTime for Rollback? Longer time means more risk",
                "service_offering": "fe2c2286a8e3e210e2ca594979e38503",
                "requested_by": "7bb874b897b34610cc5331200153afa7",
                "u_affected_customers": "07e79318db1cd110761e5fc4e2961901",
                "u_detailed_validation_steps": "Test",
                "u_communication_plan": "Test",
                "start_date": "2026-03-27 03:23:44",
                "end_date": "2026-03-27 03:23:50"
              }
            }

          interval: "15"
          timeout: "900"
